import { describe, it, expect } from 'vitest'
import { Buffer } from 'node:buffer'
import sharp from 'sharp'
import { canonicalizeImage } from './canonicalize'

// Limits generous enough that real tiny fixtures pass; tightened per-case below to
// exercise the decode-bomb guards.
const LIMITS = { maxDimension: 12000, maxPixels: 144_000_000 }

// Real tiny images generated by sharp — guaranteed decodable, no binary blobs in repo.
const realPng = (color = { r: 255, g: 0, b: 0 }) =>
  sharp({ create: { width: 2, height: 2, channels: 3, background: color } }).png().toBuffer()
const realJpeg = (color = { r: 0, g: 255, b: 0 }) =>
  sharp({ create: { width: 2, height: 2, channels: 3, background: color } }).jpeg().toBuffer()
const realWebp = (color = { r: 0, g: 0, b: 255 }) =>
  sharp({ create: { width: 2, height: 2, channels: 3, background: color } }).webp().toBuffer()
const realGif = (color = { r: 255, g: 255, b: 0 }) =>
  sharp({ create: { width: 2, height: 2, channels: 3, background: color } }).gif().toBuffer()
const realAvif = (color = { r: 255, g: 0, b: 255 }) =>
  sharp({ create: { width: 2, height: 2, channels: 3, background: color } }).avif().toBuffer()

// A real 2-frame animated GIF (red frame + green frame) — multi-page.
const realAnimatedGif = async (): Promise<Buffer> => {
  // raw 2-pixel-tall buffer, pageHeight 1 → 2 frames of 1×1 RGB
  const raw = Buffer.from([255, 0, 0, 0, 255, 0])
  return sharp(raw, { raw: { width: 1, height: 2, channels: 3, pageHeight: 1 } })
    .gif({ loop: 0, delay: [100, 100] })
    .toBuffer()
}

describe('canonicalizeImage — real images accepted (P1-A allowlist)', () => {
  it('real PNG → ok, image/png, canonical is a valid PNG', async () => {
    const bytes = await realPng()
    const out = await canonicalizeImage(bytes, LIMITS)
    expect(out.kind).toBe('ok')
    if (out.kind !== 'ok') return
    expect(out.mimeType).toBe('image/png')
    expect(out.width).toBe(2)
    expect(out.height).toBe(2)
    expect(out.pages).toBe(1)
    // canonical is decodable as png (round-trip)
    const reMeta = await sharp(out.canonicalBytes).metadata()
    expect(reMeta.format).toBe('png')
    expect(reMeta.width).toBe(2)
  })

  it('real JPEG → ok image/jpeg', async () => {
    const out = await canonicalizeImage(await realJpeg(), LIMITS)
    expect(out.kind).toBe('ok')
    if (out.kind !== 'ok') return
    expect(out.mimeType).toBe('image/jpeg')
  })

  it('real WebP → ok image/webp', async () => {
    const out = await canonicalizeImage(await realWebp(), LIMITS)
    expect(out.kind).toBe('ok')
    if (out.kind !== 'ok') return
    expect(out.mimeType).toBe('image/webp')
  })

  it('real GIF (static, 1 frame) → ok image/gif', async () => {
    const out = await canonicalizeImage(await realGif(), LIMITS)
    expect(out.kind).toBe('ok')
    if (out.kind !== 'ok') return
    expect(out.mimeType).toBe('image/gif')
    expect(out.pages).toBe(1)
  })

  it('real AVIF → ok image/avif (sharp reports heif; normalized)', async () => {
    const out = await canonicalizeImage(await realAvif(), LIMITS)
    expect(out.kind).toBe('ok')
    if (out.kind !== 'ok') return
    expect(out.mimeType).toBe('image/avif')
  })
})

describe('canonicalizeImage — animated GIF/WebP preserve frames (P1-A)', () => {
  it('animated GIF → ok, pages preserved across re-encode', async () => {
    const bytes = await realAnimatedGif()
    // sanity: the input IS animated
    const inMeta = await sharp(bytes, { animated: true }).metadata()
    expect(inMeta.pages).toBe(2)
    const out = await canonicalizeImage(bytes, LIMITS)
    expect(out.kind).toBe('ok')
    if (out.kind !== 'ok') return
    expect(out.mimeType).toBe('image/gif')
    expect(out.pages).toBe(2)
    // the canonical bytes still hold 2 frames (re-encode did NOT collapse)
    const canMeta = await sharp(out.canonicalBytes, { animated: true }).metadata()
    expect(canMeta.pages).toBe(2)
  })
})

describe('canonicalizeImage — 4 third-round 200-false-positives → 415 (P1-A root fix)', () => {
  // Each of these passed the OLD magic-byte sniffer as a vetted image (200) but is
  // NOT a real decodable image. sharp's full decode rejects them all.

  it('JPEG header (SOI+APP0/JFIF) + trailing <script> → unsupported (no scan data)', async () => {
    const polyglot = Buffer.concat([
      Buffer.from([0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10, 0x4a, 0x46, 0x49, 0x46]),
      Buffer.from('<script>alert(1)</script>'),
    ])
    const out = await canonicalizeImage(polyglot, LIMITS)
    expect(out.kind).toBe('unsupported')
  })

  it('16-byte RIFF/WEBP shell (no VP8 bitstream) → unsupported', async () => {
    const shell = Buffer.concat([Buffer.from('RIFF'), Buffer.from([0x08, 0x00, 0x00, 0x00]), Buffer.from('WEBPVP8 ')])
    const out = await canonicalizeImage(shell, LIMITS)
    expect(out.kind).toBe('unsupported')
  })

  it('24-byte residual PNG (sig + partial IHDR, no IDAT) → unsupported', async () => {
    const residual = Buffer.concat([
      Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]), // sig
      Buffer.from([0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01]), // partial IHDR
    ])
    const out = await canonicalizeImage(residual, LIMITS)
    expect(out.kind).toBe('unsupported')
  })

  it('14-byte residual GIF (magic + LSD + trailer, no image data) → unsupported', async () => {
    const residual = Buffer.from([
      0x47, 0x49, 0x46, 0x38, 0x39, 0x61, // 'GIF89a'
      0x01, 0x00, 0x01, 0x00, // width=1, height=1
      0x00, 0x00, 0x00, // packed (no GCT) + bg + aspect
      0x3b, // trailer
    ])
    const out = await canonicalizeImage(residual, LIMITS)
    expect(out.kind).toBe('unsupported')
  })
})

describe('canonicalizeImage — polyglot / trailing payload (P1-A)', () => {
  it('decodable PNG + trailing <script> → ok (trailing stripped; canonical is clean)', async () => {
    const real = await realPng({ r: 12, g: 34, b: 56 })
    const polyglot = Buffer.concat([real, Buffer.from('<script>alert(1)</script>')])
    const out = await canonicalizeImage(polyglot, LIMITS)
    expect(out.kind).toBe('ok')
    if (out.kind !== 'ok') return
    // canonical is a clean PNG without the trailing script — re-decode confirms
    expect((await sharp(out.canonicalBytes).metadata()).format).toBe('png')
    // canonical is shorter than the polyglot (trailing stripped) and is NOT the raw input
    expect(out.canonicalBytes.length).toBeLessThan(polyglot.length)
    expect(out.canonicalBytes.equals(polyglot)).toBe(false)
  })

  it('SVG (script-carrying) → unsupported', async () => {
    const svg = Buffer.from(`<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>`)
    expect((await canonicalizeImage(svg, LIMITS)).kind).toBe('unsupported')
  })

  it('HTML → unsupported', async () => {
    const html = Buffer.from('<!DOCTYPE html><html><body><script>alert(1)</script></body></html>')
    expect((await canonicalizeImage(html, LIMITS)).kind).toBe('unsupported')
  })

  it('PDF → unsupported', async () => {
    const pdf = Buffer.from('%PDF-1.4\n%\xe2\xe3\xcf\xd3\n1 0 obj<<>>endobj')
    expect((await canonicalizeImage(pdf, LIMITS)).kind).toBe('unsupported')
  })
})

describe('canonicalizeImage — decode-bomb guards (P1-A)', () => {
  it('per-frame dimension over maxDimension → too-large/dimensions', async () => {
    // A real 3×3 PNG with maxDimension=2 → 3 > 2 → too-large.
    const big = await sharp({ create: { width: 3, height: 3, channels: 3, background: { r: 1, g: 2, b: 3 } } }).png().toBuffer()
    const out = await canonicalizeImage(big, { maxDimension: 2, maxPixels: 144_000_000 })
    expect(out.kind).toBe('too-large')
    if (out.kind !== 'too-large') return
    expect(out.reason).toBe('dimensions')
    expect(out.width).toBe(3)
  })

  it('total pixels over maxPixels → too-large/pixels', async () => {
    // 4×4 = 16 pixels, maxPixels=10 → too-large.
    const big = await sharp({ create: { width: 4, height: 4, channels: 3, background: { r: 4, g: 5, b: 6 } } }).png().toBuffer()
    const out = await canonicalizeImage(big, { maxDimension: 12000, maxPixels: 10 })
    expect(out.kind).toBe('too-large')
    if (out.kind !== 'too-large') return
    expect(out.reason).toBe('pixels')
  })

  it('empty bytes → unsupported (decode-failed)', async () => {
    expect((await canonicalizeImage(Buffer.from([]), LIMITS)).kind).toBe('unsupported')
  })
})

describe('canonicalizeImage — canonical determinism + dedup-by-content (P1-A)', () => {
  it('two differently-compressed PNGs of the SAME pixels → identical canonical bytes', async () => {
    // Same 2×2 red, different PNG compression levels → different input bytes but
    // identical decoded pixels, so sharp's default re-encode produces identical canonical.
    const pngA = await sharp({ create: { width: 2, height: 2, channels: 3, background: { r: 255, g: 0, b: 0 } } })
      .png({ compressionLevel: 9 })
      .toBuffer()
    const pngB = await sharp({ create: { width: 2, height: 2, channels: 3, background: { r: 255, g: 0, b: 0 } } })
      .png({ compressionLevel: 1 })
      .toBuffer()
    expect(pngA.equals(pngB)).toBe(false) // sanity: inputs differ
    const outA = await canonicalizeImage(pngA, LIMITS)
    const outB = await canonicalizeImage(pngB, LIMITS)
    expect(outA.kind).toBe('ok')
    expect(outB.kind).toBe('ok')
    if (outA.kind !== 'ok' || outB.kind !== 'ok') return
    // identical canonical → same sha256 → the store dedups (assetId = sha256(canonical))
    expect(outA.canonicalBytes.equals(outB.canonicalBytes)).toBe(true)
  })

  it('different images → different canonical bytes', async () => {
    const outA = await canonicalizeImage(await realPng({ r: 255, g: 0, b: 0 }), LIMITS)
    const outB = await canonicalizeImage(await realPng({ r: 0, g: 0, b: 255 }), LIMITS)
    if (outA.kind !== 'ok' || outB.kind !== 'ok') throw new Error('expected ok')
    expect(outA.canonicalBytes.equals(outB.canonicalBytes)).toBe(false)
  })
})
